# Generated by Django 3.1 on 2021-05-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('method', models.TextField(max_length=2000)),
                ('outlet', models.CharField(choices=[('The Nest', 'The Nest'), ('Madara', 'Madara'), ('Pizza Mozzo', 'Pizza Mozzo'), ('breakfast', 'Breakfast'), ('Room Service', 'Room Service'), ('Recipes', 'Recipes')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ing')),
                ('qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.unit_qty')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.unit')),
            ],
        ),
    ]
