# Generated by Django 3.1 on 2021-05-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_unit',
            name='ingr',
        ),
        migrations.RemoveField(
            model_name='recipe_unit',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='recipe_unit',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recipe_unit',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Ing',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Recipe_Unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Unit_qty',
        ),
    ]
