# Generated by Django 3.1 on 2021-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0002_auto_20210502_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('recipe', models.TextField(max_length=2000)),
                ('method', models.TextField(max_length=2000)),
                ('outlet', models.CharField(choices=[('The Nest', 'The Nest'), ('Madara', 'Madara'), ('Pizza Mozzo', 'Pizza Mozzo'), ('breakfast', 'Breakfast'), ('Room Service', 'Room Service'), ('Recipes', 'Recipes')], max_length=100)),
            ],
        ),
    ]
