# Generated by Django 3.1 on 2021-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('msg', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ing',
        ),
    ]
