# Generated by Django 3.1 on 2021-05-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_sub_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_recipe',
        ),
    ]
