# Generated by Django 3.1 on 2021-05-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_sub_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_recipe',
            name='sub_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_title', to='recipe.recipe'),
        ),
    ]
