# Generated by Django 3.2.2 on 2021-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outlet',
            field=models.CharField(choices=[('The Nest', 'Afternoon Tea'), ('Madara', 'Madara'), ('Pizza Mozzo', 'Banqueting'), ('breakfast', 'Breakfast'), ('Room Service', 'Room Service'), ('Recipes', 'Recipes')], max_length=100),
        ),
    ]
