# Generated by Django 3.2.2 on 2021-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20211030_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
