# Generated by Django 3.2.2 on 2022-01-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20220117_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='sub_recipe',
            name='archived',
        ),
    ]
